### ISSUE TITLE
StringIndexOutOfBoundsException error at parse time

### ISSUE THREAD

**Issue by Zir0-93** [hadii-tech/clarpse#111]
The following exception is thrown when parsing the attached Java file.
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -3
	at java.lang.String.substring(String.java:1931)
	at com.github.javaparser.ast.expr.TextBlockLiteralExpr.lambda$stripIndentOfLines$3(TextBlockLiteralExpr.java:153)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:748)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.expr.TextBlockLiteralExpr.accept(TextBlockLiteralExpr.java:81)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:1587)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.expr.MemberValuePair.accept(MemberValuePair.java:81)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:1572)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.expr.NormalAnnotationExpr.accept(NormalAnnotationExpr.java:74)
	at com.github.javaparser.printer.PrettyPrintVisitor.printMemberAnnotations(PrettyPrintVisitor.java:93)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:984)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:106)
	at com.github.javaparser.printer.PrettyPrintVisitor.printMembers(PrettyPrintVisitor.java:83)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:312)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:100)
	at com.github.javaparser.printer.PrettyPrinter.print(PrettyPrinter.java:43)
	at com.github.javaparser.ast.Node.toString(Node.java:282)
	at com.hadii.clarpse.listener.JavaTreeListener.createComponent(JavaTreeListener.java:113)
	at com.hadii.clarpse.listener.JavaTreeListener.visit(JavaTreeListener.java:162)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:100)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$43(VoidVisitorAdapter.java:175)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:290)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:175)
	at com.hadii.clarpse.compiler.ClarpseJavaCompiler.compile(ClarpseJavaCompiler.java:49)
	at com.hadii.clarpse.compiler.ClarpseProject.parseRawData(ClarpseProject.java:18)
	at com.hadii.clarpse.compiler.ClarpseProject.result(ClarpseProject.java:29)
	at com.hadii.striff.parse.ParsedProject.model(ParsedProject.java:17)
	at striff.test.StriffOperationLocalTest.getGitHubRepoModel(StriffOperationLocalTest.java:86)
	at striff.test.StriffOperationLocalTest.manualTest(StriffOperationLocalTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.ju
[ParameterizedTestIntegrationTests.java.txt](https://github.com/hadii-tech/clarpse/files/7850194/ParameterizedTestIntegrationTests.java.txt)
[ParameterizedTestIntegrationTests.java.txt](https://github.com/hadii-tech/clarpse/files/7850195/ParameterizedTestIntegrationTests.java.txt)
[ParameterizedTestIntegrationTests.java.txt](https://github.com/hadii-tech/clarpse/files/7850197/ParameterizedTestIntegrationTests.java.txt)
nit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
java.lang.StringIndexOutOfBoundsException: String index out of range: -3
	at java.lang.String.substring(String.java:1931)
	at com.github.javaparser.ast.expr.TextBlockLiteralExpr.lambda$stripIndentOfLines$3(TextBlockLiteralExpr.java:153)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:748)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.expr.TextBlockLiteralExpr.accept(TextBlockLiteralExpr.java:81)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:540)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.body.VariableDeclarator.accept(VariableDeclarator.java:149)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:506)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.body.FieldDeclaration.accept(FieldDeclaration.java:118)
	at com.github.javaparser.printer.PrettyPrintVisitor.printMembers(PrettyPrintVisitor.java:83)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:312)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:52)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:100)
	at com.github.javaparser.printer.PrettyPrinter.print(PrettyPrinter.java:43)
	at com.github.javaparser.ast.Node.toString(Node.java:282)
	at com.hadii.clarpse.listener.JavaTreeListener.createComponent(JavaTreeListener.java:113)
	at com.hadii.clarpse.listener.JavaTreeListener.visit(JavaTreeListener.java:162)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:100)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$43(VoidVisitorAdapter.java:175)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:290)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:175)
	at com.hadii.clarpse.compiler.ClarpseJavaCompiler.compile(ClarpseJavaCompiler.java:49)
	at com.hadii.clarpse.compiler.ClarpseProject.parseRawData(ClarpseProject.java:18)
	at com.hadii.clarpse.compiler.ClarpseProject.result(ClarpseProject.java:29)
	at com.hadii.striff.parse.ParsedProject.model(ParsedProject.java:17)
	at striff.test.StriffOperationLocalTest.getGitHubRepoModel(StriffOperationLocalTest.java:86)
	at striff.test.StriffOperationLocalTest.manualTest(StriffOperationLocalTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by Zir0-93** [comment]
[ParameterizedTestIntegrationTests.java.txt](https://github.com/hadii-tech/clarpse/files/7850201/ParameterizedTestIntegrationTests.java.txt)
